name: Playwright Tests
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 */10 * *' # every 10 days

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-node@v5
      with:
        node-version: lts/*

    # NPM Cache to speed up installs
    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Install dependencies only if not in cache
    - name: Install dependencies
      run: npm ci

    # Load Browsers cache from Playwright
    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    # Install browsers only if not in cache
    - name: Install Playwright Browsers
      run: |
        if [ ! -d "~/.cache/ms-playwright" ]; then
          npx playwright install --with-deps
        else
          echo "Playwright cache restored, skipping install"
        fi

    - name: Run Playwright tests
      run: |
        if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
          npx cucumber-js --tags "@debug"
        else
          npx cucumber-js
        fi

    - name: Publish JUnit Report
      uses: mikepenz/action-junit-report@v5
      if: always()
      with:
        report_paths: 'reports/junit-results.xml'
        token: ${{ github.token }}
